export const CategoryLabels = {
  noticia: {
    aviso: "Aviso",
    noticia: "Noticia",
    urgente: "Urgente",
    obra: "Obras",
    medioambiente: "Medio Ambiente",
    cultura: "Cultura",
    deporte: "Deporte",
    general: "General",
  },
  evento: {
    fiesta: "Fiestas",
    cultural: "Cultural",
    deportivo: "Deportivo",
    mercado: "Mercado",
    reunion: "Reunión",
    formacion: "Formación",
    otro: "Otro",
  },
  tramite: {
    padron: "Padrón",
    licencias: "Licencias",
    impuestos: "Impuestos",
    urbanismo: "Urbanismo",
    servicios: "Servicios",
    subvenciones: "Subvenciones",
    otro: "Otro",
  },
  incidencia: {
    viales: "Viales",
    alumbrado: "Alumbrado",
    parques: "Parques",
    agua: "Agua",
    residuos: "Residuos",
    edificios: "Edificios",
    trafico: "Tráfico",
    otro: "Otro",
  },
  estado: {
    pendiente: "Pendiente",
    en_proceso: "En proceso",
    resuelta: "Resuelta",
    cerrada: "Cerrada",
    rechazada: "Rechazada",
  },
};
